apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-pv-from-snapshot
  namespace: test-ebs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-03ed8c8c74348a197 