apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-pv-from-snapshot
  namespace: test-ebs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "gp2"
  volumeName: ebs-pv-from-snapshot